env: "local"
grpc_port: 44044
gateway_port: 8080
postgres:
  user: "postgres"
  password: "admin"
  host: "localhost"
  port: 5432
  dbname: "sync"
  sslmode: "disable"
tokens:
  access_ttl: 15m
  refresh_ttl: 720h
  redis_addr: "127.0.0.1:6379"
  secret: "watafuk"
github_auth:
  github_client_id: "Ov23lixxG2PWaJNVT8qH"
  github_client_secret: "1cc1b64771a9b0d4f34cb306c22d644d0d228783"